- name: INstall nginx
  hosts: WEB
  become: true
  tasks:
    - name: INstall nginx
      ansible.builtin.yum:
        name: nginx
        state: latest

    - name: INstall nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes