- name: Conditions
  hosts: all
  connection: local
  vars:
    fruit: true
    vegetable: false
  tasks:
    - name: Fruits
      ansible.builtin.debug:
        msg: Fruit is - Apple
      when: fruit is true

    - name: Vegetables
      ansible.builtin.debug:
        msg: Vegetable is - Carrot
      when: vegetable is true