- name: Variable Types
  hosts: localhost
  connection: local
  vars:
    fruits:
      - orange
      - apple
  tasks:
    - name: Print Fruits
      ansible.builtin.debug:
        msg: Fruit Name - {{ item }}
      loop: "{{ fruits }}"

    - name: Print Fruits Local Values
      ansible.builtin.debug:
        msg: Fruit Name - {{ item }}
      loop:
        - banana
        - Dragon

    - name: Print Fruits Local Values
      ansible.builtin.debug:
        msg: Fruit Name - {{ item }}
      loop:
        - { name: banana, quantity: 100 }
        - { name: dragon, quantity: 200}
